---
- name: Ensure machine credential exists
  awx.awx.credential:
    name: "{{ awx_machine_credential.name }}"
    organization: "{{ awx_organization_name }}"
    credential_type: Machine
    inputs: "{{ awx_machine_credential_inputs }}"
    update_secrets: "{{ awx_update_encrypted_credential_values }}"
    state: present
  no_log: true
  when: awx_machine_credential.manage | bool

- name: Ensure platform secrets credential exists
  awx.awx.credential:
    name: "{{ awx_platform_secrets_credential.name }}"
    organization: "{{ awx_organization_name }}"
    credential_type: "{{ awx_platform_credential_type.name }}"
    inputs: "{{ awx_platform_secrets_inputs }}"
    update_secrets: "{{ awx_update_encrypted_credential_values }}"
    state: present
  no_log: true
  when: awx_platform_secrets_credential.manage | bool

- name: Ensure SCM credential exists when requested
  awx.awx.credential:
    name: "{{ awx_scm_credential.name }}"
    organization: "{{ awx_organization_name }}"
    credential_type: Source Control
    inputs: "{{ awx_scm_credential_inputs }}"
    update_secrets: "{{ awx_update_encrypted_credential_values }}"
    state: present
  no_log: true
  when: awx_scm_credential.manage | bool

- name: Ensure AWX self API credential exists
  awx.awx.credential:
    name: "{{ awx_controller_api_credential.name }}"
    organization: "{{ awx_organization_name }}"
    credential_type: "{{ awx_controller_api_credential_type.name }}"
    inputs: "{{ awx_controller_api_credential_inputs }}"
    update_secrets: "{{ awx_update_encrypted_credential_values }}"
    state: present
  no_log: true
  when: awx_controller_api_credential.manage | bool
