---
nginx_setup_server_name: "{{ ansible_facts.hostname | default(inventory_hostname) }}"
nginx_setup_root: "/var/www/html/{{ ansible_facts.hostname | default(inventory_hostname) }}"
nginx_setup_listen_port: 80
nginx_setup_enable_basic_auth: false
nginx_setup_htpasswd_path: "/etc/nginx/conf.d/{{ ansible_facts.hostname | default(inventory_hostname) }}.htpasswd"
nginx_setup_auth_user: admin
nginx_setup_auth_password: ""
nginx_setup_sample_files: []
nginx_setup_manage_firewall: false
nginx_setup_firewall_source_cidr: 127.0.0.1/32
