---

- name: Get existing users
  ansible.builtin.getent:
    database: passwd

- name: Add sudoers file for privileged users
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ privileged_access_user }}"
    content: "{{ privileged_access_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  loop: "{{ privileged_access_sudo_users }}"
  loop_control:
    loop_var: privileged_access_user
  when: privileged_access_user in ansible_facts.getent_passwd
  become: true

- name: Add sudoers file for privileged users
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ privileged_access_user }}"
    content: "{{ privileged_access_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  loop: "{{ privileged_access_sudo_users }}"
  loop_control:
    loop_var: privileged_access_user
  become: true

- name: Reset SSH connection after sudo changes
  ansible.builtin.meta: reset_connection

- name: Verify connection after sudo changes
  ansible.builtin.ping:
