---
- name: Change Ansible Port & User Variable 
  set_fact:
    ansible_port: 22
    ansible_user: nima
  tags:
    - priviledged_access-config

- name: Get `Existing users`
  ansible.builtin.getent:
    database: passwd
  tags:
    - priviledged_access-config

- name: Add `sudoers` File For Privileged Users
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ privileged_access_user }}"
    content: "{{ privileged_access_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  loop: "{{ privileged_access_sudo_users }}"
  loop_control:
    loop_var: privileged_access_user
  when: privileged_access_user in ansible_facts.getent_passwd
  become: true
  tags:
    - priviledged_access-config

- name: Reset SSH connection after sudo changes
  ansible.builtin.meta: reset_connection
  tags:
    - priviledged_access-config

- name: Verify connection after sudo changes
  ansible.builtin.ping:
  tags:
    - priviledged_access-config
