linux_baseline_packages:
- git

# If `mirror_apt_active` gets false, it won't add our repositories
linux_baseline_manage_apt_mirror: true
linux_baseline_mirror_domain_name: repo.nima.local

# Debian Apt Proxy Set
linux_baseline_manage_apt_proxy: true
linux_baseline_apt_proxy_address: main.nima.local
apt_proxy_port1: 10808
apt_proxy_port2: 12334
linux_baseline_apt_proxy_port: "{{ apt_proxy_port2 }}"

# `sshd` Configuration
linux_baseline_sshd_config:
  Port: "{{ ssh_port | default(ansible_port | default(22)) }}"
  ListenAddress: "{{ ansible_host }}"
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: "nima"
  AllowGroups: "nima"

# `fail2ban` Configuration
linux_baseline_fail2ban:
  bantime: 10m
  findtime: 10m
  maxretry: 5

# Setion Timeout Setting (Seconds)
linux_baseline_timeout_seconds: 600

# `auditd` Vars
linux_baseline_auditd_apply_audit_rules: 'yes'
linux_baseline_auditd_action_mail_acct: root
linux_baseline_auditd_admin_space_left_action: suspend
linux_baseline_auditd_disk_error_action: suspend
linux_baseline_auditd_disk_full_action: suspend
linux_baseline_auditd_max_log_file: 8
linux_baseline_auditd_max_log_file_action: keep_logs
linux_baseline_auditd_mode: 1
linux_baseline_auditd_num_logs: 5
linux_baseline_auditd_space_left: 75
linux_baseline_auditd_space_left_action: email
linux_baseline_grub_audit_backlog_cmdline: audit_backlog_limit=8192
linux_baseline_grub_audit_cmdline: audit=1


