---

linux_baseline_debian_release: "{{ ansible_distribution_release | default('stable') }}"
linux_baseline_ubuntu_release: "{{ ansible_distribution_release | default('stable') }}"

linux_baseline_iptables_extra_rules: []
