---

all:
  vars:
    ansible_port: 8090
    ansible_user: root
  children:
    managed_linux:
      hosts:
        dhcp-server-1:
          ansible_host: 192.168.252.2
          ansible_port: 22
        dns-server-1:
          ansible_host: 192.168.252.3
        main:
          ansible_host: main
          ansible_port: 2201
        tools-server-1:
          ansible_host: tools-server-1
        tools-server-2:
          ansible_host: tools-server-2
        backup-server-1:
          ansible_host: backup-server-1
        repo-server-1:
          ansible_host: repo-server-1
        runner-server-1:
          ansible_host: runner-server-1
        awx-server-1:
          ansible_host: awx-server-1
        semaphore-server-1:
          ansible_host: semaphore-server-1
        elk-server-1:
          ansible_host: elk-server-1
        elk-server-2:
          ansible_host: elk-server-2
        monlog-server-1:
          ansible_host: monlog-server-1
        monlog-server-2:
          ansible_host: monlog-server-2
        it-tools-server-1:
          ansible_host: it-tools-server-1
        web-server-1:
          ansible_host: web-server-1
        web-server-2:
          ansible_host: web-server-2
        web-server-3:
          ansible_host: web-server-3
        web-server-4:
          ansible_host: web-server-4
        web-server-5:
          ansible_host: web-server-5
        wordpress-server-1:
          ansible_host: wordpress-server-1
        wordpress-server-2:
          ansible_host: wordpress-server-2
        wordpress-server-3:
          ansible_host: wordpress-server-3
        database-server-1:
          ansible_host: database-server-1
        database-server-2:
          ansible_host: database-server-2
        database-server-3:
          ansible_host: database-server-3
        database-proxy-server-1:
          ansible_host: database-proxy-server-1
        database-proxy-server-2:
          ansible_host: database-proxy-server-2
        loadbalancer-server-1:
          ansible_host: loadbalancer-server-1
        loadbalancer-server-2:
          ansible_host: loadbalancer-server-2
        registry-server-1:
          ansible_host: registry-server-1
        nfs-server-1:
          ansible_host: nfs-server-1
        management-server-1:
          ansible_host: management-server-1.nima.local
          ansible_port: 22

    tmp-servers:
      hosts:
        ubu-tmp-srv-01:
    test_servers:
      hosts:
        foo-server-1:
        bar-server-1:

    tools_servers:
      hosts:
        tools-server-1:
        tools-server-2:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        awx-server-1:
        nfs-server-1:
        it-tools-server-1:
        dhcp-server-1:
        dns-server-1:

    gitlab_servers:
      hosts:
        repo-server-1:
        runner-server-1:

    web_servers:
      children:
        all_web_servers:
          hosts:
            web-server-1:
            web-server-2:
            web-server-3:
            web-server-4:
            web-server-5:
            wordpress-server-1:
            wordpress-server-2:
            dns-server-1:
        nginx_servers:
          hosts:
            web-server-1:
            web-server-2:
        wordpress_servers:
          hosts:            
            wordpress-server-1:
            wordpress-server-2:
            wordpress-server-3:

    database_servers:
      children:
        all_database_servers:
          hosts:
            database-server-1:
            database-server-2:
            database-server-3:

    database_proxy_servers:
      hosts:
        database-proxy-server-1:
        database-proxy-server-1:

    loadbalancer_servers:
      hosts:
        loadbalancer-server-1:
        loadbalancer-server-2:

    docker_servers:
      hosts:
        main:
        ubu-tmp-srv-01:
        dns-server-1:
        tools-server-1:
        tools-server-2:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        nfs-server-1:
        awx-server-1:
        elk-server-1:
        elk-server-2:
        monlog-server-1:
        monlog-server-2:
        foo-server-1:
        bar-server-1:
        web-server-1:
        web-server-2:
        web-server-3:
        web-server-4:
        web-server-5:
        wordpress-server-1:
        wordpress-server-2:
        wordpress-server-3:
        database-server-1:
        database-server-2:
        database-server-3:
        loadbalancer-server-1:
        loadbalancer-server-2:
        management-server-1:
        database-proxy-server-1:
        database-proxy-server-2:
  
    monitoring_servers:
      children:
        elk_servers:
          hosts:
            elk-server-1:
            elk-server-2:
        monlog_servers:
          hosts:
            monlog-server-1:
            monlog-server-2:

    observability_clients:
      children:
        promtail_clients:
          hosts:
            web-server-1:
            web-server-2:
            web-server-3:
            web-server-4:
            web-server-5:
            wordpress-server-1:
            wordpress-server-2:
        elastic_clients:
          hosts: {}

    it-servers:
      network-servers:
        hosts:
          it-tools-server-1:
          dhcp-server-1:
          dns-server-1:

    lab:
      children:
        managed_linux:
