---
all:
  vars:
    ansible_port: 8090
    ansible_user: root
  children:
    managed_linux:
      hosts:
        main:
          ansible_host: 192.168.252.20
          ansible_port: 2201
        tools-server-1:
          ansible_host: 192.168.252.31
        tools-server-2:
          ansible_host: 192.168.252.36
        backup-server-1:
          ansible_host: 192.168.252.32
        repo-server-1:
          ansible_host: 192.168.252.33
        runner-server-1:
          ansible_host: 192.168.252.34
        awx-server-1:
          ansible_host: 192.168.252.35
        elk-server-1:
          ansible_host: 192.168.252.41
        elk-server-2:
          ansible_host: 192.168.252.42
        monlog-server-1:
          ansible_host: 192.168.252.43
        monlog-server-2:
          ansible_host: 192.168.252.44
        foo-server-1:
          ansible_host: 192.168.252.51
        bar-server-1:
          ansible_host: 192.168.252.52
        web-server-1:
          ansible_host: 192.168.252.61
        web-server-2:
          ansible_host: 192.168.252.62
        web-server-3:
          ansible_host: 192.168.252.63
        web-server-4:
          ansible_host: 192.168.252.64
        web-server-5:
          ansible_host: 192.168.252.65
          ansible_port: 22

    test_servers:
      hosts:
        foo-server-1:
        bar-server-1:

    tools_servers:
      hosts:
        tools-server-1:
        tools-server-2:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        awx-server-1:

    gitlab_servers:
      hosts:
        repo-server-1:
        runner-server-1:

    web_servers:
      children:
        web_servers:
          hosts:
            web-server-1:
            web-server-2:
            web-server-3:
            web-server-4:
            web-server-5:

    docker_servers:
      hosts:
        main:
        tools-server-1:
        tools-server-2:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        awx-server-1:
        elk-server-1:
        elk-server-2:
        monlog-server-1:
        monlog-server-2:
        foo-server-1:
        bar-server-1:
        web-server-1:
        web-server-2:
        web-server-3:
        web-server-4:
        web-server-5:

    monitoring_servers:
      children:
        elk_servers:
          hosts:
            elk-server-1:
            elk-server-2:
        monlog_servers:
          hosts:
            monlog-server-1:
            monlog-server-2:

    observability_clients:
      children:
        promtail_clients:
          hosts:
            web-server-1:
            web-server-2:
            web-server-3:
            web-server-4:
            web-server-5:
        elastic_clients:
          hosts: {}

    lab:
      children:
        managed_linux:
