---
all:
  vars:
    ansible_port: 8090
  children:
    managed_linux:
      hosts:
        main:
          ansible_host: 192.168.250.19
          ansible_port: 2201
        tools-server-1:
          ansible_host: 192.168.250.31
        backup-server-1:
          ansible_host: 192.168.250.32
        repo-server-1:
          ansible_host: 192.168.250.33
        runner-server-1:
          ansible_host: 192.168.250.34
        awx-server-1:
          ansible_host: 192.168.250.35
        elk-server-1:
          ansible_host: 192.168.250.41
        elk-server-2:
          ansible_host: 192.168.250.42
        monlog-server-1:
          ansible_host: 192.168.250.43
        monlog-server-2:
          ansible_host: 192.168.250.44
        foo-server-1:
          ansible_host: 192.168.250.51
        bar-server-1:
          ansible_host: 192.168.250.52
        nginx-server-1:
          ansible_host: 192.168.250.61
        nginx-server-2:
          ansible_host: 192.168.250.62
        nginx-server-3:
          ansible_host: 192.168.250.63
        nginx-server-4:
          ansible_host: 192.168.250.64
        nginx-server-5:
          ansible_host: 192.168.250.65
          ansible_port: 8090

    test_servers:
      hosts:
        foo-server-1:
        bar-server-1:

    tools_servers:
      hosts:
        tools-server-1:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        awx-server-1:

    gitlab_servers:
      hosts:
        repo-server-1:
        runner-server-1:

    web_servers:
      children:
        nginx_servers:
          hosts:
            nginx-server-1:
            nginx-server-2:
            nginx-server-3:
            nginx-server-4:
            nginx-server-5:

    docker_servers:
      hosts:
        main:
        tools-server-1:
        backup-server-1:
        repo-server-1:
        runner-server-1:
        awx-server-1:
        elk-server-1:
        elk-server-2:
        monlog-server-1:
        monlog-server-2:
        foo-server-1:
        bar-server-1:
        nginx-server-1:
        nginx-server-2:
        nginx-server-3:
        nginx-server-4:
        nginx-server-5:

    monitoring_servers:
      children:
        elk_servers:
          hosts:
            elk-server-1:
            elk-server-2:
        monlog_servers:
          hosts:
            monlog-server-1:
            monlog-server-2:

    observability_clients:
      children:
        promtail_clients:
          hosts:
            nginx-server-1:
            nginx-server-2:
            nginx-server-3:
            nginx-server-4:
            nginx-server-5:
        elastic_clients:
          hosts: {}

    lab:
      children:
        managed_linux:
