main_dir: /opt/services
linux_baseline_timezone: Asia/Tehran

# `SSH` Variables
rollout_batch_size: "20%"

linux_baseline_hosts_allow_entries:
    - { service: sshd, source: main.nima.local }
    - { service: sshd, source: runner-server-1.nima.local }
    - { service: sshd, source: awx-server-1.nima.local }

# Root Users
privileged_access_sudo_users:
  - nima
  - debian

# Session Timeout Setting (Seconds)
linux_baseline_timeout_seconds: 600


# `fail2ban` Configuration
linux_baseline_fail2ban:
  bantime: 10m
  findtime: 10m
  maxretry: 5
linux_baseline_fail2ban_ignoreip:
    - 127.0.0.1/8
    - ::1
    - 192.168.56.1/32

# `limit.conf` Variables
linux_baseline_limit_nofile_hard: 1024
linux_baseline_limit_nofile_soft: 512
linux_baseline_limit_nproc_hard: 1024
linux_baseline_limit_nproc_soft: 512

# `sysctll` Configuration Variables
linux_baseline_sysctl:
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.forwarding: 1
  net.ipv6.conf.all.forwarding: 1
  vm.max_map_count: 262144
  fs.file-max: 1500000
  net.ipv4.tcp_tw_reuse: 1
  net.netfilter.nf_conntrack_tcp_timeout_established: 900
  net.netfilter.nf_conntrack_tcp_timeout_close_wait: 10
  net.netfilter.nf_conntrack_tcp_timeout_syn_recv: 30
linux_baseline_manage_lynis: true
linux_baseline_lynis_git_version: "3.1.5"

# `lynis` Variables
lynis_version: '3.1.5'
lynis_name: 'lynis-{{ lynis_version }}'
lynis_tarball_url: 'https://downloads.cisofy.com/lynis/{{ lynis_name }}.tar.gz'
lynis_tarball_unpackdest: '/opt'
lynis_tarball_unpackdest_dir: '{{ lynis_tarball_unpackdest }}/lynis'
lynis_tarball_dest: '{{ lynis_tarball_unpackdest_dir }}/{{ lynis_name }}.tar.gz'
