# `iptables` Configuration
linux_baseline_iptables:
    network_adapter_access:
        - lo
    udp_port_access: []
    trusted_ip:
      - 192.168.252.20
      - 192.168.252.35
    trusted_ip_range:
      #- 192.168.252.0/24
    icmp_access:
      - 192.168.252.20/32
    
linux_baseline_manage_iptables: true
linux_baseline_sshd_config:
  Port: 8090
linux_baseline_iptables_rules_file: /etc/iptables/rules.v4
linux_baseline_iptables_extra_rules: []
