---
# Example only. Never commit real values.
secret_platform_http_proxy: ""
secret_file_service_username: "webadmin"
secret_file_service_password: "e52ZuNWY4KxF4WhLELUD"
secret_loki_password: ""
secret_nginx_auth_password: ""
