---
argument_specs:
  main:
    short_description: Apply a common Debian/Ubuntu Linux platform baseline.
    options:
      linux_baseline_manage_root_bashrc: {type: bool, default: false}
      linux_baseline_manage_apt_mirror: {type: bool, default: false}
      linux_baseline_allow_insecure_apt_mirror: {type: bool, default: false}
      linux_baseline_mirror_domain_name: {type: str}
      linux_baseline_manage_apt_proxy: {type: bool, default: false}
      linux_baseline_apt_proxy_address: {type: str, default: ""}
      linux_baseline_apt_proxy_port: {type: int, default: 0}
      linux_baseline_upgrade_packages: {type: bool, default: false}
      linux_baseline_timezone: {type: str, default: UTC}
      linux_baseline_nameservers: {type: list, elements: str, default: []}
      linux_baseline_dns: {type: str, default: ""}
      linux_baseline_fallback_dns: {type: str, default: ""}
      linux_baseline_dnssec: {type: str}
      linux_baseline_dns_over_tls: {type: str}
      linux_baseline_domain_name: {type: str}
      linux_baseline_hosts_entries: {type: list, elements: dict, default: []}
      linux_baseline_hosts_allow_entries: {type: list, elements: dict, default: []}
      linux_baseline_fail2ban_ignoreip: {type: list, elements: str, default: []}
      linux_baseline_packages: {type: list, elements: str, default: []}
      linux_baseline_sshd_config: {type: dict}
      linux_baseline_manage_iptables: {type: bool, default: false}
      linux_baseline_iptables_rules_file: {type: str}
      linux_baseline_iptables_extra_rules: {type: list, elements: str, default: []}
      linux_baseline_iptables: {type: dict}
      linux_baseline_timeout_seconds: {type: int, default: 600}
      linux_baseline_fail2ban: {type: dict}
      linux_baseline_sysctl: {type: dict, default: {}}
      linux_baseline_auditd_apply_audit_rules: {type: bool, default: false}
      linux_baseline_manage_lynis: {type: bool, default: false}
      linux_baseline_lynis_git_version: {type: str, default: "3.1.5"}
