---
- name: Configure Docker hosts
  hosts: "{{ target_hosts | default('docker_servers') }}"
  gather_facts: true
  become: true
  serial: "{{ rollout_batch_size | default('20%') }}"
  roles:
    - role: nima.platform.docker_engine
      tags: [docker]
