---
- name: Import `Bootstrap` Playbook
  ansible.builtin.import_playbook: bootstrap.yml

- name: Import `Baseline` Playbook
  ansible.builtin.import_playbook: baseline.yml

- name: Import `Zsh` Playbook
  ansible.builtin.import_playbook: zsh.yml

- name: Import `Docker` Playbook
  ansible.builtin.import_playbook: docker.yml

# - name: Import Nginx Playbook
#   ansible.builtin.import_playbook: nginx.yml

# - name: Import `Observability` Playbook
#   ansible.builtin.import_playbook: observability.yml
