---
- name: Import baseline playbook
  ansible.builtin.import_playbook: baseline.yml

- name: Import Docker playbook
  ansible.builtin.import_playbook: docker.yml

- name: Import Nginx playbook
  ansible.builtin.import_playbook: nginx.yml

- name: Import observability playbook
  ansible.builtin.import_playbook: observability.yml
