---
argument_specs:
  main:
    short_description: Install and configure Docker Engine on Debian-family systems.
    options:
      docker_engine_dependencies:
        type: list
        elements: str
      docker_engine_user:
        type: str
      docker_engine_repo_base_url:
        type: str
      docker_engine_repo_distribution:
        type: str
      docker_engine_repo_component:
        type: str
      docker_engine_repo_architecture:
        type: str
      docker_engine_repo_allow_insecure:
        type: bool
        default: false
      docker_engine_validate_certs:
        type: bool
        default: true
      docker_engine_packages:
        type: list
        elements: str
      docker_engine_package_state:
        type: str
        choices: [present, latest]
        default: present
      docker_engine_http_proxy:
        type: str
      docker_engine_https_proxy:
        type: str
      docker_engine_no_proxy:
        type: str
      docker_engine_log_max_file:
        type: str
      docker_engine_log_max_size:
        type: str
      docker_engine_registry_mirror:
        type: str
